---
# Personalized workstation setup for Christopher Markieta
- hosts: localhost
  become: yes
  tasks:
  - name: Copy google chrome repo data to yum.repos.d
    copy:
      src: files/etc/yum.repos.d/google-chrome.repo
      dest: /etc/yum.repos.d/google-chrome.repo
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "Fedora"
    tags: chrome

  - name: Add google chrome key
    shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    when: ansible_distribution == "Ubuntu"
    tags: chrome

  - name: Add google chrome repo
    copy: 
      content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
      dest: /etc/apt/sources.list.d/google-chrome.list
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "Ubuntu"
    tags: chrome

  - name: Upgrade all packages
    package:
      name: "*"
      state: latest
    when: ansible_distribution == "Fedora"
    tags: update

  - name: Update all packages to the latest version
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Install the 'Development tools' package group
    dnf:
      name: '@Development tools'
      state: present
    when: ansible_distribution == "Fedora"
    tags: devtools

  - name: Install build-essential
    apt:
      name: build-essential
      state: latest
    when: ansible_distribution == "Ubuntu"
    tags: devtools

  - name: Install rpmfusion repositories
    dnf: name={{ item }} state=latest
    with_items:
      - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm'
      - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm'
    when: ansible_distribution == "Fedora"
    tags: rpmfusion

  - name: Install and update packages
    package: name={{ item }} state=latest
    with_items:
      - google-chrome-stable
      - mpv
      - putty
      - redshift-gtk
      - sl
      - transmission-remote-gtk
      - terminator
      - tmux
      - vim
      - xclip
    tags: install

  - name: Create config directory for mpv
    file:
      path: /home/markieta/.config/mpv/
      state: directory
      owner: markieta
      group: markieta
      mode: 0700
    tags: mpvdir

  - name: Copy mpv config
    copy:
      src: files/home/markieta/.config/mpv/mpv.conf
      dest: /home/markieta/.config/mpv/mpv.conf
      owner: markieta
      group: markieta
      mode: 0664
    tags: mpvconf

  - name: Copy git config
    copy:
      src: files/home/markieta/.gitconfig
      dest: "{{ item }}"
      owner: root
      group: markieta
      mode: 0664
    with_items:
      - /root/.gitconfig
      - /home/markieta/.gitconfig
    tags: gitconfig

  - name: Copy .bashrc
    copy:
      src: files/home/markieta/.bashrc
      dest: /home/markieta/.bashrc
      owner: markieta
      group: markieta
      mode: 0644
    tags: bashrc

  - name: Copy terminator config
    copy:
      src: files/home/markieta/.config/terminator/config
      dest: /home/markieta/.config/terminator/config
      owner: markieta
      group: markieta
      mode: 0664
    tags: terminatorconf

  - name: Copy redshift config
    copy:
      src: files/home/markieta/.config/redshift.conf
      dest: /home/markieta/.config/redshift.conf
      owner: markieta
      group: markieta
      mode: 0664
    tags: redshiftconf

  - name: Modify sudoers to enable passwordless sudo for user markieta
    lineinfile:
      dest: /etc/sudoers
      line: 'markieta ALL=(ALL) NOPASSWD: ALL'
    tags: passwordlesssudo

  - name: Change origin url for this project from https to git to allow push
    command: /usr/bin/git remote set-url origin git@github.com:Markieta/linux-post-install.git
    tags: giturl
