---
# Personalized workstation setup for Christopher Markieta
- hosts: localhost
  become: yes
  tasks:
    - include: chrome.yml
    - include: upgrade.yml
    - include: devtools.yml
    - include: utilities.yml
