---
- hosts: localhost
  become: yes
  tasks:
  - copy:
      src: files/etc/yum.repos.d/google-chrome.repo
      dest: /etc/yum.repos.d/google-chrome.repo
      owner: root
      group: root
      mode: 0644

  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: install the 'Development tools' package group
    dnf:
      name: '@Development tools'
      state: present

  - name: install and update packages
    dnf: name={{ item }} state=latest
    with_items:
    - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm'
    - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm'
    - google-chrome-stable
    - mpv
    - putty
    - redshift-gtk
    - sl
    - transmission-remote-gtk
    - terminator
    - tmux
    - vim
    - xclip

  - file:
      path: /home/markieta/.config/mpv/
      state: directory
      owner: markieta
      group: markieta
      mode: 0700

  - copy:
      src: files/home/markieta/.config/mpv/mpv.conf
      dest: /home/markieta/.config/mpv/mpv.conf
      owner: markieta
      group: markieta
      mode: 0664

  - copy:
      src: files/home/markieta/.gitconfig
      dest: "{{ item }}"
      owner: root
      group: markieta
      mode: 0664
    with_items:
    - /root/.gitconfig
    - /home/markieta/.gitconfig

  - copy:
      src: files/home/markieta/.bashrc
      dest: /home/markieta/.bashrc
      owner: markieta
      group: markieta
      mode: 0644

  - copy:
      src: files/home/markieta/.config/terminator/config
      dest: /home/markieta/.config/terminator/config
      owner: markieta
      group: markieta
      mode: 0664

  - lineinfile:
      dest: /etc/sudoers
      line: 'markieta ALL=(ALL) NOPASSWD: ALL'
