---
- hosts: localhost
  become: sudo
  tasks:
  - copy:
      src: files/etc/yum.repos.d/google-chrome.repo
      dest: /etc/yum.repos.d/google-chrome.repo
      owner: root
      mode: 0644

  - name: install packages
    yum: name={{item}} state=latest update_cache=yes
    with_items:
    - "*"
    - '@Development Tools'
    - git
    - google-chrome-stable
#    - mpv
    - putty
    - redshift-gtk
    - sl
#    - transmission-remote-gtk
    - tree
    - terminator
    - tmux
    - vim
    - xclip

  - copy:
      src: files/home/markieta/.config/mpv/mpv.conf
      dest: /home/markieta/.config/mpv/mpv.conf
      owner: markieta
      mode: 0664

  - copy:
      src: files/home/markieta/.gitconfig
      dest: "{{item}}"
      owner: root
      mode: 0644
    with_items:
    - /root/.gitconfig
    - /home/markieta/.gitconfig
